### ISSUE TITLE
扫描完成后返回菜单页面会崩溃

### ISSUE THREAD

**Issue by BillZong** [weweier/swift-#1]
感谢作者的Demo, 帮忙解决了不少问题.
然而在示例代码中发现一个Bug: 如题
主要是因为```AVCaptureSession```对象在```viewDidLoad()```和```scanQRCode()```中多次监听```KVO```事件, 但移除的时候又仅移除了一次. 导致```KVO```匹配不对等. 麻烦做一下修正, 以飨后来读者, 谢谢.

**Comment by weweier** [comment]
谢谢提醒，已经修复
